import type { StickerId } from "@/components/stickers/artwork";

// Destinations et escales voisines, avec leur identité (DEST-05 dans le cahier des charges).

export type TypeEscale = "complete" | "fiche" | "voisine";

export type Ville = {
  id: string;
  nom: string;
  pays: string;
  /** Code ISO du pays, pour la carte du monde. */
  paysCode: string;
  code: string;
  couleur: string;
  latitude: number;
  longitude: number;
  type: TypeEscale;
  /** Pour une escale voisine : l'escale complète à laquelle elle est rattachée. */
  principale?: string;
  /** Absent tant que l'autocollant n'est pas dessiné. */
  autocollant?: StickerId;
};

export const villes: Ville[] = [
  {
    id: "rome",
    nom: "Rome",
    pays: "Italie",
    paysCode: "IT",
    code: "ROM",
    couleur: "#C47A2C",
    latitude: 41.9028,
    longitude: 12.4964,
    type: "complete",
    autocollant: "rome",
  },
  {
    id: "paris",
    nom: "Paris",
    pays: "France",
    paysCode: "FR",
    code: "PAR",
    couleur: "#7A5C45",
    latitude: 48.8566,
    longitude: 2.3522,
    type: "complete",
    autocollant: "paris",
  },
  {
    id: "lisbonne",
    nom: "Lisbonne",
    pays: "Portugal",
    paysCode: "PT",
    code: "LIS",
    couleur: "#F2C230",
    latitude: 38.7223,
    longitude: -9.1393,
    type: "fiche",
    autocollant: "lisbonne",
  },
  {
    id: "barcelone",
    nom: "Barcelone",
    pays: "Espagne",
    paysCode: "ES",
    code: "BCN",
    couleur: "#2D7AB9",
    latitude: 41.3874,
    longitude: 2.1686,
    type: "fiche",
    autocollant: "barcelone",
  },
  {
    id: "londres",
    nom: "Londres",
    pays: "Royaume-Uni",
    paysCode: "GB",
    code: "LON",
    couleur: "#D9312B",
    latitude: 51.5074,
    longitude: -0.1278,
    type: "fiche",
    autocollant: "londres",
  },
  {
    id: "amsterdam",
    nom: "Amsterdam",
    pays: "Pays-Bas",
    paysCode: "NL",
    code: "AMS",
    couleur: "#F07A1A",
    latitude: 52.3676,
    longitude: 4.9041,
    type: "fiche",
    autocollant: "amsterdam",
  },
  {
    id: "berlin",
    nom: "Berlin",
    pays: "Allemagne",
    paysCode: "DE",
    code: "BER",
    couleur: "#5BAF3F",
    latitude: 52.52,
    longitude: 13.405,
    type: "fiche",
    autocollant: "berlin",
  },
  {
    id: "bruxelles",
    nom: "Bruxelles",
    pays: "Belgique",
    paysCode: "BE",
    code: "BRU",
    couleur: "#8D99A6",
    latitude: 50.8503,
    longitude: 4.3517,
    type: "fiche",
    autocollant: "bruxelles",
  },
  {
    id: "dublin",
    nom: "Dublin",
    pays: "Irlande",
    paysCode: "IE",
    code: "DUB",
    couleur: "#1E7B45",
    latitude: 53.3498,
    longitude: -6.2603,
    type: "fiche",
    autocollant: "dublin",
  },
  {
    id: "edimbourg",
    nom: "Édimbourg",
    pays: "Écosse",
    paysCode: "GB",
    code: "EDI",
    couleur: "#7B4F9E",
    latitude: 55.9533,
    longitude: -3.1883,
    type: "fiche",
    autocollant: "edimbourg",
  },
  {
    id: "marrakech",
    nom: "Marrakech",
    pays: "Maroc",
    paysCode: "MA",
    code: "RAK",
    couleur: "#3D4FD1",
    latitude: 31.6295,
    longitude: -7.9811,
    type: "fiche",
    autocollant: "marrakech",
  },
  {
    id: "louxor",
    nom: "Louxor",
    pays: "Égypte",
    paysCode: "EG",
    code: "LXR",
    couleur: "#2A9D8F",
    latitude: 25.6872,
    longitude: 32.6396,
    type: "fiche",
    autocollant: "louxor",
  },
  {
    id: "new-york",
    nom: "New York",
    pays: "États-Unis",
    paysCode: "US",
    code: "NYC",
    couleur: "#F6B10A",
    latitude: 40.7128,
    longitude: -74.006,
    type: "fiche",
    autocollant: "new-york",
  },
  {
    id: "montreal",
    nom: "Montréal",
    pays: "Canada",
    paysCode: "CA",
    code: "YUL",
    couleur: "#7FB2D6",
    latitude: 45.5017,
    longitude: -73.5673,
    type: "fiche",
    autocollant: "montreal",
  },
  {
    id: "tokyo",
    nom: "Tokyo",
    pays: "Japon",
    paysCode: "JP",
    code: "TYO",
    couleur: "#E58FB0",
    latitude: 35.6762,
    longitude: 139.6503,
    type: "fiche",
    autocollant: "tokyo",
  },
  {
    id: "florence",
    nom: "Florence",
    pays: "Italie",
    paysCode: "IT",
    code: "FLR",
    couleur: "#A85F24",
    latitude: 43.7696,
    longitude: 11.2558,
    type: "voisine",
    principale: "rome",
  },
  {
    id: "pise",
    nom: "Pise",
    pays: "Italie",
    paysCode: "IT",
    code: "PSA",
    couleur: "#D9994A",
    latitude: 43.7228,
    longitude: 10.4017,
    type: "voisine",
    principale: "rome",
  },
  {
    id: "lille",
    nom: "Lille",
    pays: "France",
    paysCode: "FR",
    code: "LIL",
    couleur: "#8C4F3A",
    latitude: 50.6292,
    longitude: 3.0573,
    type: "voisine",
    principale: "paris",
    autocollant: "lille",
  },
  {
    id: "lyon",
    nom: "Lyon",
    pays: "France",
    paysCode: "FR",
    code: "LYS",
    couleur: "#956E50",
    latitude: 45.764,
    longitude: 4.8357,
    type: "voisine",
    principale: "paris",
  },
  {
    id: "strasbourg",
    nom: "Strasbourg",
    pays: "France",
    paysCode: "FR",
    code: "SXB",
    couleur: "#96625F",
    latitude: 48.5734,
    longitude: 7.7521,
    type: "voisine",
    principale: "paris",
  },
];

export const destinations = villes.filter((v) => v.type !== "voisine");
export const escalesVoisines = villes.filter((v) => v.type === "voisine");
